server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include:
      - actuator
      - oauth
      - cloud
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  # database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_MASTER_DATASOURCE_URL}
    username: ${SPRING_MASTER_DATASOURCE_USERNAME}
    password: ${SPRING_MASTER_DATASOURCE_PASSWORD}
    slaves:
      slave1:
        name: SLAVE1
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${SPRING_SLAVE_DATASOURCE_USERNAME}
        password: ${SPRING_SLAVE_DATASOURCE_PASSWORD}
        url: ${SPRING_SLAVE_DATASOURCE_URL}
  # JPA 설정
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace