# JWT 설정
jwt:
  issuer: yong7317
  secret-key: ${JWT_SECRET_KEY}
  expiry-seconds:
    access-token: 1800
    refresh-token: 604800

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
  mvc:
    static-path-pattern: /static/**