server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  include:
    - oauth
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  # database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA 설정
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  issuer: yong7317
  secret-key: ${JWT_SECRET_KEY}
  expiry-seconds:
    access-token: 100000
    refresh-token: 604800