server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active:
      - ${ACTIVE_PROFILE}
    include:
      - cloud
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  file-dir:

  # database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA 설정
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  # redis 설정
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

spring-doc:
  title: Gooding
  version: v1
  description: description
  api-docs:
    enabled: true
    swagger-ui:
      enabled: true
      tagsSorter: alpha
      operations-sorter: alpha
      display-request-duration: true

jwt:
  issuer: yong7317
  secret-key: ${JWT_SECRET_KEY}
  expiry-seconds:
    access-token: 1800
    refresh-token: 604800
---
spring:
  environment: "local"
  config:
    activate:
      on-profile: "local"
  file-dir: /src/main/resources/static/files/
---
spring:
  environment: "development"
  config:
    activate:
      on-profile: "development"
  file-dir: /home/ec2-user/files/