server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active:
      - ${ACTIVE_PROFILE}
    include:
      - security

  # database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # redis 설정
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

spring-doc:
  title: Gooding
  version: v1
  description: description