server:
  port: 8083

management:
  server:
    port: 9292
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${PROFILES_ACTIVE}
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  # JPA 설정
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  # Mail 설정
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp

jwt:
  issuer: yong7317
  secret-key: ${JWT_SECRET_KEY}
  expiry-seconds:
    access-token: 100000
    refresh-token: 604800

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URI}

cloud:
  aws:
    endpoint: ${AWS_ENDPOINT}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace