version: "3.8"

services:
  local-elasticsearch-master:
    build:
      context: ./elk/elasticsearch
      dockerfile: Dockerfile
    container_name: local-elasticsearch-master
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es-master
      - discovery.seed_hosts=local-elasticsearch-data1
      - cluster.initial_master_nodes=es-master
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      my-network:
        ipv4_address: 172.28.0.9

  local-elasticsearch-data1:
    build:
      context: ./elk/elasticsearch
      dockerfile: Dockerfile
    container_name: local-elasticsearch-data1
    environment:
      - node.name=es-data1
      - discovery.seed_hosts=local-elasticsearch-master
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      my-network:
        ipv4_address: 172.28.0.10

  local-elasticsearch-coordinating:
    build:
      context: ./elk/elasticsearch
      dockerfile: Dockerfile
    container_name: local-elasticsearch-coordinating
    environment:
      - node.name=es-coordinating
      - cluster.name=docker-cluster
      - discovery.seed_hosts=local-elasticsearch-master,local-elasticsearch-data1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    networks:
      my-network:
        ipv4_address: 172.28.0.11

  local-kibana:
    build:
      context: ./elk/kibana
      dockerfile: Dockerfile
    container_name: local-kibana
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      my-network:
        ipv4_address: 172.28.0.12
    depends_on:
      - local-elasticsearch-master

  local-logstash:
    build:
      context: ./elk/logstash
      dockerfile: Dockerfile
    container_name: local-logstash
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      my-network:
        ipv4_address: 172.28.0.13
    depends_on:
      - local-elasticsearch-master

  local-metricbeat:
    build:
      context: ./elk/metricbeat
      dockerfile: Dockerfile
    container_name: local-metricbeat
    volumes:
      - ./elk/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./elk/metricbeat/config/elasticsearch-xpack.yml:/usr/share/metricbeat/modules.d/elasticsearch-xpack.yml
    ports:
      - "5066:5066"
    networks:
      my-network:
        ipv4_address: 172.28.0.14
    depends_on:
      - local-elasticsearch-master
      - local-kibana

volumes:
  elasticsearch_data:
    driver: local
  metricbeat_data:
    driver: local

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16