version: "3.8"

services:
  local-sonar:
    image: sonarqube:9.9.2-community
    ports:
      - '9000:9000'
      - '9092:9092'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://local-postgresql:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      my-network:
        ipv4_address: 172.28.0.6
  local-postgresql:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      my-network:
        ipv4_address: 172.28.0.7

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16