version: "3.8"

services:
  local-zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      my-network:
        ipv4_address: 172.28.0.5

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16